license_id: cc-by
methodology: "https://viewsforecasting.org/early-warning-system/definitions/"
caveats: None
dataset_source: Violence & Impacts Early-Warning System
package_creator: HDX Data Systems Team
private: False
maintainer: "b682f6f7-cd7e-4bd4-8aa7-f74138dc6313" # berylnyamgeroh
owner_org: "03d86d43-6add-4e30-a510-72a475e57fa3" # views
data_update_frequency: 30
notes: The Violence & Impacts Early-Warning System (VIEWS) is an award-winning conflict prediction system that generates monthly forecasts for violent conflicts across the world up to three years in advance. It is supported by the iterative research and development activities undertaken by the VIEWS consortium.
